#pragma once

constexpr size_t WEATHER_TC_FILES_COUNT = 15;
constexpr size_t TC_TIME_SAMPLES = 13;

enum Regions
{
	GLOBAL,
	URBAN,
	TC_REGIONS_COUNT
};

enum TimeCycleVar_e
{
	TCVAR_LIGHT_DIR_COL_R = 0,
	TCVAR_LIGHT_DIR_COL_G,
	TCVAR_LIGHT_DIR_COL_B,
	TCVAR_LIGHT_DIR_MULT,

	TCVAR_LIGHT_DIRECTIONAL_AMB_COL_R,
	TCVAR_LIGHT_DIRECTIONAL_AMB_COL_G,
	TCVAR_LIGHT_DIRECTIONAL_AMB_COL_B,
	TCVAR_LIGHT_DIRECTIONAL_AMB_INTENSITY,
	TCVAR_LIGHT_DIRECTIONAL_AMB_INTENSITY_MULT,
	TCVAR_LIGHT_DIRECTIONAL_AMB_BOUNCE_ENABLED,

	TCVAR_LIGHT_AMB_DOWN_WRAP,

	TCVAR_LIGHT_NATURAL_AMB_DOWN_COL_R,
	TCVAR_LIGHT_NATURAL_AMB_DOWN_COL_G,
	TCVAR_LIGHT_NATURAL_AMB_DOWN_COL_B,
	TCVAR_LIGHT_NATURAL_AMB_DOWN_INTENSITY,

	TCVAR_LIGHT_NATURAL_AMB_BASE_COL_R,
	TCVAR_LIGHT_NATURAL_AMB_BASE_COL_G,
	TCVAR_LIGHT_NATURAL_AMB_BASE_COL_B,
	TCVAR_LIGHT_NATURAL_AMB_BASE_INTENSITY,
	TCVAR_LIGHT_NATURAL_AMB_BASE_INTENSITY_MULT,

	TCVAR_LIGHT_NATURAL_PUSH,
	TCVAR_LIGHT_AMBIENT_BAKE_RAMP,

	TCVAR_LIGHT_ARTIFICIAL_INT_AMB_DOWN_COL_R,
	TCVAR_LIGHT_ARTIFICIAL_INT_AMB_DOWN_COL_G,
	TCVAR_LIGHT_ARTIFICIAL_INT_AMB_DOWN_COL_B,
	TCVAR_LIGHT_ARTIFICIAL_INT_AMB_DOWN_INTENSITY,

	TCVAR_LIGHT_ARTIFICIAL_INT_AMB_BASE_COL_R,
	TCVAR_LIGHT_ARTIFICIAL_INT_AMB_BASE_COL_G,
	TCVAR_LIGHT_ARTIFICIAL_INT_AMB_BASE_COL_B,
	TCVAR_LIGHT_ARTIFICIAL_INT_AMB_BASE_INTENSITY,

	TCVAR_LIGHT_ARTIFICIAL_EXT_AMB_DOWN_COL_R,
	TCVAR_LIGHT_ARTIFICIAL_EXT_AMB_DOWN_COL_G,
	TCVAR_LIGHT_ARTIFICIAL_EXT_AMB_DOWN_COL_B,
	TCVAR_LIGHT_ARTIFICIAL_EXT_AMB_DOWN_INTENSITY,

	TCVAR_LIGHT_ARTIFICIAL_EXT_AMB_BASE_COL_R,
	TCVAR_LIGHT_ARTIFICIAL_EXT_AMB_BASE_COL_G,
	TCVAR_LIGHT_ARTIFICIAL_EXT_AMB_BASE_COL_B,
	TCVAR_LIGHT_ARTIFICIAL_EXT_AMB_BASE_INTENSITY,

	TCVAR_PED_LIGHT_COL_R,
	TCVAR_PED_LIGHT_COL_G,
	TCVAR_PED_LIGHT_COL_B,
	TCVAR_PED_LIGHT_MULT,
	TCVAR_PED_LIGHT_DIRECTION_X,
	TCVAR_PED_LIGHT_DIRECTION_Y,
	TCVAR_PED_LIGHT_DIRECTION_Z,

	TCVAR_LIGHT_AMB_OCC_MULT,
	TCVAR_LIGHT_AMB_OCC_MULT_PED,
	TCVAR_LIGHT_AMB_OCC_MULT_VEH,
	TCVAR_LIGHT_AMB_OCC_MULT_PROP,
	TCVAR_LIGHT_AMB_VOLUMES_IN_DIFFUSE,
	TCVAR_LIGHT_SSAO_INTEN,
	TCVAR_LIGHT_SSAO_TYPE,
	TCVAR_LIGHT_SSAO_CP_STRENGTH,
	TCVAR_LIGHT_SSAO_QS_STRENGTH,

	TCVAR_LIGHT_PED_RIM_MULT,
	TCVAR_LIGHT_DYNAMIC_BAKE_TWEAK,
	TCVAR_LIGHT_VEHICLE_SECOND_SPEC_OVERRIDE,
	TCVAR_LIGHT_VEHICLE_INTENSITY_SCALE,

	TCVAR_LIGHT_DIRECTION_OVERRIDE,
	TCVAR_LIGHT_DIRECTION_OVERRIDE_OVERRIDES_SUN,
	TCVAR_SUN_DIRECTION_X,
	TCVAR_SUN_DIRECTION_Y,
	TCVAR_SUN_DIRECTION_Z,
	TCVAR_MOON_DIRECTION_X,
	TCVAR_MOON_DIRECTION_Y,
	TCVAR_MOON_DIRECTION_Z,

	TCVAR_LIGHT_RAY_COL_R,
	TCVAR_LIGHT_RAY_COL_G,
	TCVAR_LIGHT_RAY_COL_B,
	TCVAR_LIGHT_RAY_MULT,
	TCVAR_LIGHT_RAY_UNDERWATER_MULT,
	TCVAR_LIGHT_RAY_DIST,
	TCVAR_LIGHT_RAY_HEIGHTFALLOFF,
	TCVAR_LIGHT_RAY_HEIGHTFALLOFFSTART,

	TCVAR_LIGHT_RAY_ADD_REDUCER,
	TCVAR_LIGHT_RAY_BLIT_SIZE,
	TCVAR_LIGHT_RAY_RAY_LENGTH,

	// post fx variables
	TCVAR_POSTFX_EXPOSURE,
	TCVAR_POSTFX_EXPOSURE_MIN,
	TCVAR_POSTFX_EXPOSURE_MAX,

	TCVAR_POSTFX_BRIGHT_PASS_THRESH_WIDTH,
	TCVAR_POSTFX_BRIGHT_PASS_THRESH,
	TCVAR_POSTFX_INTENSITY_BLOOM,

	TCVAR_POSTFX_CORRECT_COL_R,
	TCVAR_POSTFX_CORRECT_COL_G,
	TCVAR_POSTFX_CORRECT_COL_B,
	TCVAR_POSTFX_CORRECT_CUTOFF,

	TCVAR_POSTFX_SHIFT_COL_R,
	TCVAR_POSTFX_SHIFT_COL_G,
	TCVAR_POSTFX_SHIFT_COL_B,
	TCVAR_POSTFX_SHIFT_CUTOFF,

	TCVAR_POSTFX_DESATURATION,

	TCVAR_POSTFX_NOISE,
	TCVAR_POSTFX_NOISE_SIZE,

	TCVAR_POSTFX_TONEMAP_FILMIC_OVERRIDE_DARK,
	TCVAR_POSTFX_TONEMAP_FILMIC_EXPOSURE_DARK,
	TCVAR_POSTFX_TONEMAP_FILMIC_A_DARK,
	TCVAR_POSTFX_TONEMAP_FILMIC_B_DARK,
	TCVAR_POSTFX_TONEMAP_FILMIC_C_DARK,
	TCVAR_POSTFX_TONEMAP_FILMIC_D_DARK,
	TCVAR_POSTFX_TONEMAP_FILMIC_E_DARK,
	TCVAR_POSTFX_TONEMAP_FILMIC_F_DARK,
	TCVAR_POSTFX_TONEMAP_FILMIC_W_DARK,

	TCVAR_POSTFX_TONEMAP_FILMIC_OVERRIDE_BRIGHT,
	TCVAR_POSTFX_TONEMAP_FILMIC_EXPOSURE_BRIGHT,
	TCVAR_POSTFX_TONEMAP_FILMIC_A_BRIGHT,
	TCVAR_POSTFX_TONEMAP_FILMIC_B_BRIGHT,
	TCVAR_POSTFX_TONEMAP_FILMIC_C_BRIGHT,
	TCVAR_POSTFX_TONEMAP_FILMIC_D_BRIGHT,
	TCVAR_POSTFX_TONEMAP_FILMIC_E_BRIGHT,
	TCVAR_POSTFX_TONEMAP_FILMIC_F_BRIGHT,
	TCVAR_POSTFX_TONEMAP_FILMIC_W_BRIGHT,

	TCVAR_POSTFX_VIGNETTING_INTENSITY,
	TCVAR_POSTFX_VIGNETTING_RADIUS,
	TCVAR_POSTFX_VIGNETTING_CONTRAST,
	TCVAR_POSTFX_VIGNETTING_COL_R,
	TCVAR_POSTFX_VIGNETTING_COL_G,
	TCVAR_POSTFX_VIGNETTING_COL_B,

	TCVAR_POSTFX_GRAD_TOP_COL_R,
	TCVAR_POSTFX_GRAD_TOP_COL_G,
	TCVAR_POSTFX_GRAD_TOP_COL_B,

	TCVAR_POSTFX_GRAD_MIDDLE_COL_R,
	TCVAR_POSTFX_GRAD_MIDDLE_COL_G,
	TCVAR_POSTFX_GRAD_MIDDLE_COL_B,

	TCVAR_POSTFX_GRAD_BOTTOM_COL_R,
	TCVAR_POSTFX_GRAD_BOTTOM_COL_G,
	TCVAR_POSTFX_GRAD_BOTTOM_COL_B,

	TCVAR_POSTFX_GRAD_MIDPOINT,
	TCVAR_POSTFX_GRAD_TOP_MIDDLE_MIDPOINT,
	TCVAR_POSTFX_GRAD_MIDDLE_BOTTOM_MIDPOINT,

	TCVAR_POSTFX_SCANLINEINTENSITY,
	TCVAR_POSTFX_SCANLINE_FREQUENCY_0,
	TCVAR_POSTFX_SCANLINE_FREQUENCY_1,
	TCVAR_POSTFX_SCANLINE_SPEED,

	TCVAR_POSTFX_MOTIONBLUR_LENGTH,
	TCVAR_DOF_FAR,

	TCVAR_DOF_BLUR_MID,
	TCVAR_DOF_BLUR_FAR,
	TCVAR_DOF_ENABLE_HQDOF,
	TCVAR_DOF_HQDOF_SMALLBLUR,
	TCVAR_DOF_HQDOF_SHALLOWDOF,
	TCVAR_DOF_HQDOF_NEARPLANE_OUT,
	TCVAR_DOF_HQDOF_NEARPLANE_IN,
	TCVAR_DOF_HQDOF_FARPLANE_OUT,
	TCVAR_DOF_HQDOF_FARPLANE_IN,

	TCVAR_ENV_BLUR_IN,
	TCVAR_ENV_BLUR_OUT,
	TCVAR_ENV_BLUR_SIZE,

	TCVAR_BOKEH_BRIGHTNESS_MIN,
	TCVAR_BOKEH_BRIGHTNESS_MAX,
	TCVAR_BOKEH_FADE_MIN,
	TCVAR_BOKEH_FADE_MAX,

	TCVAR_NV_LIGHT_DIR_MULT,
	TCVAR_NV_LIGHT_AMB_DOWN_MULT,
	TCVAR_NV_LIGHT_AMB_BASE_MULT,

	TCVAR_NV_LOWLUM,
	TCVAR_NV_HIGHLUM,
	TCVAR_NV_TOPLUM,

	TCVAR_NV_SCALERLUM,

	TCVAR_NV_OFFSETLUM,
	TCVAR_NV_OFFSETLOWLUM,
	TCVAR_NV_OFFSETHIGHLUM,

	TCVAR_NV_NOISELUM,
	TCVAR_NV_NOISELOWLUM,
	TCVAR_NV_NOISEHIGHLUM,

	TCVAR_NV_BLOOMLUM,

	TCVAR_NV_COLORLUM_R,
	TCVAR_NV_COLORLUM_G,
	TCVAR_NV_COLORLUM_B,
	TCVAR_NV_COLORLOWLUM_R,
	TCVAR_NV_COLORLOWLUM_G,
	TCVAR_NV_COLORLOWLUM_B,
	TCVAR_NV_COLORHIGHLUM_R,
	TCVAR_NV_COLORHIGHLUM_G,
	TCVAR_NV_COLORHIGHLUM_B,

	TCVAR_HH_RANGESTART,
	TCVAR_HH_RANGEEND,
	TCVAR_HH_MININTENSITY,
	TCVAR_HH_MAXINTENSITY,
	TCVAR_HH_DISPU,
	TCVAR_HH_DISPV,
	TCVAR_HH_TEX1_USCALE,
	TCVAR_HH_TEX1_VSCALE,
	TCVAR_HH_TEX1_UOFFSET,
	TCVAR_HH_TEX1_VOFFSET,
	TCVAR_HH_TEX2_USCALE,
	TCVAR_HH_TEX2_VSCALE,
	TCVAR_HH_TEX2_UOFFSET,
	TCVAR_HH_TEX2_VOFFSET,
	TCVAR_HH_TEX1_OFFSET,
	TCVAR_HH_TEX1_FREQUENCY,
	TCVAR_HH_TEX1_AMPLITUDE,
	TCVAR_HH_TEX1_SCROLLING,
	TCVAR_HH_TEX2_OFFSET,
	TCVAR_HH_TEX2_FREQUENCY,
	TCVAR_HH_TEX2_AMPLITUDE,
	TCVAR_HH_TEX2_SCROLLING,

	TCVAR_LENS_DISTORTION_COEFF,
	TCVAR_LENS_DISTORTION_CUBE_COEFF,
	TCVAR_LENS_CHROMATIC_ABERRATION_COEFF,
	TCVAR_LENS_CHROMATIC_ABERRATION_CUBE_COEFF,

	TCVAR_LENS_ARTEFACTS_INTENSITY,
	TCVAR_LENS_ARTEFACTS_INTENSITY_MIN_EXP,
	TCVAR_LENS_ARTEFACTS_INTENSITY_MAX_EXP,

	TCVAR_BLUR_VIGNETTING_RADIUS,
	TCVAR_BLUR_VIGNETTING_INTENSITY,

	TCVAR_SCREEN_BLUR_INTENSITY,

	TCVAR_SKY_ZENITH_TRANSITION_POSITION,
	TCVAR_SKY_ZENITH_TRANSITION_EAST_BLEND,
	TCVAR_SKY_ZENITH_TRANSITION_WEST_BLEND,

	TCVAR_SKY_ZENITH_BLEND_START,

	TCVAR_SKY_ZENITH_COL_R,
	TCVAR_SKY_ZENITH_COL_G,
	TCVAR_SKY_ZENITH_COL_B,
	TCVAR_SKY_ZENITH_COL_INTEN,

	TCVAR_SKY_ZENITH_TRANSITION_COL_R,
	TCVAR_SKY_ZENITH_TRANSITION_COL_G,
	TCVAR_SKY_ZENITH_TRANSITION_COL_B,
	TCVAR_SKY_ZENITH_TRANSITION_COL_INTEN,

	TCVAR_SKY_AZIMUTH_TRANSITION_POSITION,

	TCVAR_SKY_AZIMUTH_EAST_COL_R,
	TCVAR_SKY_AZIMUTH_EAST_COL_G,
	TCVAR_SKY_AZIMUTH_EAST_COL_B,
	TCVAR_SKY_AZIMUTH_EAST_COL_INTEN,

	TCVAR_SKY_AZIMUTH_TRANSITION_COL_R,
	TCVAR_SKY_AZIMUTH_TRANSITION_COL_G,
	TCVAR_SKY_AZIMUTH_TRANSITION_COL_B,
	TCVAR_SKY_AZIMUTH_TRANSITION_COL_INTEN,

	TCVAR_SKY_AZIMUTH_WEST_COL_R,
	TCVAR_SKY_AZIMUTH_WEST_COL_G,
	TCVAR_SKY_AZIMUTH_WEST_COL_B,
	TCVAR_SKY_AZIMUTH_WEST_COL_INTEN,

	TCVAR_SKY_HDR,

	TCVAR_SKY_PLANE_COL_R,
	TCVAR_SKY_PLANE_COL_G,
	TCVAR_SKY_PLANE_COL_B,
	TCVAR_SKY_PLANE_INTEN,

	TCVAR_SKY_SUN_COL_R,
	TCVAR_SKY_SUN_COL_G,
	TCVAR_SKY_SUN_COL_B,

	TCVAR_SKY_SUN_DISC_COL_R,
	TCVAR_SKY_SUN_DISC_COL_G,
	TCVAR_SKY_SUN_DISC_COL_B,

	TCVAR_SKY_SUN_DISC_SIZE,

	TCVAR_SKY_SUN_HDR,

	TCVAR_SKY_SUN_MIEPHASE,
	TCVAR_SKY_SUN_MIESCATTER,
	TCVAR_SKY_SUN_MIE_INTENSITY_MULT,

	TCVAR_SKY_SUN_INFLUENCE_RADIUS,
	TCVAR_SKY_SUN_SCATTER_INTEN,

	TCVAR_SKY_MOON_COL_R,
	TCVAR_SKY_MOON_COL_G,
	TCVAR_SKY_MOON_COL_B,

	TCVAR_SKY_MOON_DISC_SIZE,

	TCVAR_SKY_MOON_ITEN,
	TCVAR_SKY_STARS_ITEN,

	TCVAR_SKY_MOON_INFLUENCE_RADIUS,
	TCVAR_SKY_MOON_SCATTER_INTEN,

	TCVAR_SKY_CLOUD_GEN_FREQUENCY,
	TCVAR_SKY_CLOUD_GEN_SCALE,
	TCVAR_SKY_CLOUD_GEN_THRESHOLD,
	TCVAR_SKY_CLOUD_GEN_SOFTNESS,
	TCVAR_SKY_CLOUD_DENSITY_MULT,
	TCVAR_SKY_CLOUD_DENSITY_BIAS,

	TCVAR_SKY_CLOUD_MID_COL_R,
	TCVAR_SKY_CLOUD_MID_COL_G,
	TCVAR_SKY_CLOUD_MID_COL_B,

	TCVAR_SKY_CLOUD_BASE_COL_R,
	TCVAR_SKY_CLOUD_BASE_COL_G,
	TCVAR_SKY_CLOUD_BASE_COL_B,

	TCVAR_SKY_CLOUD_BASE_STRENGTH,

	TCVAR_SKY_CLOUD_SHADOW_COL_R,
	TCVAR_SKY_CLOUD_SHADOW_COL_G,
	TCVAR_SKY_CLOUD_SHADOW_COL_B,

	TCVAR_SKY_CLOUD_SHADOW_STRENGTH,
	TCVAR_SKY_CLOUD_GEN_DENSITY_OFFSET,
	TCVAR_SKY_CLOUD_OFFSET,

	TCVAR_SKY_CLOUD_OVERALL_STRENGTH,
	TCVAR_SKY_CLOUD_OVERALL_COLOR,
	TCVAR_SKY_CLOUD_EDGE_STRENGTH,

	TCVAR_SKY_CLOUD_FADEOUT,
	TCVAR_SKY_CLOUD_HDR,
	TCVAR_SKY_CLOUD_DITHER_STRENGTH,

	TCVAR_SKY_SMALL_CLOUD_COL_R,
	TCVAR_SKY_SMALL_CLOUD_COL_G,
	TCVAR_SKY_SMALL_CLOUD_COL_B,

	TCVAR_SKY_SMALL_CLOUD_DETAIL_STRENGTH,
	TCVAR_SKY_SMALL_CLOUD_DETAIL_SCALE,
	TCVAR_SKY_SMALL_CLOUD_DENSITY_MULT,
	TCVAR_SKY_SMALL_CLOUD_DENSITY_BIAS,

	TCVAR_CLOUD_SHADOW_DENSITY,
	TCVAR_CLOUD_SHADOW_SOFTNESS,
	TCVAR_CLOUD_SHADOW_OPACITY,

	TCVAR_DIRECTIONAL_SHADOW_NUM_CASCADES,
	TCVAR_DIRECTIONAL_SHADOW_DISTANCE_MULTIPLIER,
	TCVAR_DIRECTIONAL_SHADOW_SOFTNESS,
	TCVAR_DIRECTIONAL_SHADOW_CASCADE0_SCALE,

	TCVAR_SPRITE_BRIGHTNESS,
	TCVAR_SPRITE_SIZE,
	TCVAR_SPRITE_CORONA_SCREENSPACE_EXPANSION,
	TCVAR_LENSFLARE_VISIBILITY,
	TCVAR_SPRITE_DISTANT_LIGHT_TWINKLE,

	TCVAR_WATER_REFLECTION_FIRST,
	TCVAR_WATER_REFLECTION = TCVAR_WATER_REFLECTION_FIRST,
	TCVAR_WATER_REFLECTION_FAR_CLIP,
	TCVAR_WATER_REFLECTION_LOD,
	TCVAR_WATER_REFLECTION_SKY_FLOD_RANGE,
	TCVAR_WATER_REFLECTION_LOD_RANGE_ENABLED,
	TCVAR_WATER_REFLECTION_LOD_RANGE_HD_START,
	TCVAR_WATER_REFLECTION_LOD_RANGE_HD_END,
	TCVAR_WATER_REFLECTION_LOD_RANGE_ORPHANHD_START,
	TCVAR_WATER_REFLECTION_LOD_RANGE_ORPHANHD_END,
	TCVAR_WATER_REFLECTION_LOD_RANGE_LOD_START,
	TCVAR_WATER_REFLECTION_LOD_RANGE_LOD_END,
	TCVAR_WATER_REFLECTION_LOD_RANGE_SLOD1_START,
	TCVAR_WATER_REFLECTION_LOD_RANGE_SLOD1_END,
	TCVAR_WATER_REFLECTION_LOD_RANGE_SLOD2_START,
	TCVAR_WATER_REFLECTION_LOD_RANGE_SLOD2_END,
	TCVAR_WATER_REFLECTION_LOD_RANGE_SLOD3_START,
	TCVAR_WATER_REFLECTION_LOD_RANGE_SLOD3_END,
	TCVAR_WATER_REFLECTION_LOD_RANGE_SLOD4_START,
	TCVAR_WATER_REFLECTION_LOD_RANGE_SLOD4_END,
	TCVAR_WATER_REFLECTION_HEIGHT_OFFSET,
	TCVAR_WATER_REFLECTION_HEIGHT_OVERRIDE,
	TCVAR_WATER_REFLECTION_HEIGHT_OVERRIDE_AMOUNT,
	TCVAR_WATER_REFLECTION_DISTANT_LIGHT_INTENSITY,
	TCVAR_WATER_REFLECTION_CORONA_INTENSITY,
	TCVAR_WATER_REFLECTION_LAST = TCVAR_WATER_REFLECTION_CORONA_INTENSITY,

	TCVAR_WATER_FOGLIGHT,
	TCVAR_WATER_INTERIOR,
	TCVAR_WATER_ENABLEFOGSTREAMING,
	TCVAR_WATER_FOAM_INTENSITY_MULT,
	TCVAR_WATER_DRYING_SPEED_MULT,
	TCVAR_WATER_SPECULAR_INTENSITY,

	TCVAR_MIRROR_REFLECTION_LOCAL_LIGHT_INTENSITY,

	TCVAR_FOG_START,
	TCVAR_FOG_NEAR_COL_R,
	TCVAR_FOG_NEAR_COL_G,
	TCVAR_FOG_NEAR_COL_B,
	TCVAR_FOG_NEAR_COL_A,

	TCVAR_FOG_SUN_COL_R,
	TCVAR_FOG_SUN_COL_G,
	TCVAR_FOG_SUN_COL_B,
	TCVAR_FOG_SUN_COL_A,
	TCVAR_FOG_SUN_LIGHTING_CALC_POW,

	TCVAR_FOG_MOON_COL_R,
	TCVAR_FOG_MOON_COL_G,
	TCVAR_FOG_MOON_COL_B,
	TCVAR_FOG_MOON_COL_A,
	TCVAR_FOG_MOON_LIGHTING_CALC_POW,

	TCVAR_FOG_FAR_COL_R,
	TCVAR_FOG_FAR_COL_G,
	TCVAR_FOG_FAR_COL_B,
	TCVAR_FOG_FAR_COL_A,

	TCVAR_FOG_DENSITY,
	TCVAR_FOG_HEIGHT_FALLOFF,
	TCVAR_FOG_BASE_HEIGHT,
	TCVAR_FOG_ALPHA,
	TCVAR_FOG_HORIZON_TINT_SCALE,
	TCVAR_FOG_HDR,

	TCVAR_FOG_HAZE_COL_R,
	TCVAR_FOG_HAZE_COL_G,
	TCVAR_FOG_HAZE_COL_B,
	TCVAR_FOG_HAZE_DENSITY,
	TCVAR_FOG_HAZE_ALPHA,
	TCVAR_FOG_HAZE_HDR,
	TCVAR_FOG_HAZE_START,

	TCVAR_FOG_SHAPE_LOW,	
	TCVAR_FOG_SHAPE_HIGH,
	TCVAR_FOG_LOG_10_MIN_VISIBILIY, 
	TCVAR_FOG_SHAPE_WEIGHT_0,	
	TCVAR_FOG_SHAPE_WEIGHT_1,		
	TCVAR_FOG_SHAPE_WEIGHT_2,
	TCVAR_FOG_SHAPE_WEIGHT_3,

	TCVAR_FOG_SHADOW_AMOUNT, 
	TCVAR_FOG_SHADOW_FALLOFF, 
	TCVAR_FOG_SHADOW_BASE_HEIGHT,

	TCVAR_FOG_VOLUME_RANGE,
	TCVAR_FOG_VOLUME_FADE_RANGE,
	TCVAR_FOG_VOLUME_INTENSITY_SCALE,
	TCVAR_FOG_VOLUME_SIZE_SCALE,

	TCVAR_FOG_FOGRAY_CONTRAST,
	TCVAR_FOG_FOGRAY_INTENSITY,
	TCVAR_FOG_FOGRAY_DENSITY,
	TCVAR_FOG_FOGRAY_NEARFADE,
	TCVAR_FOG_FOGRAY_FARFADE,

	TCVAR_REFLECTION_LOD_RANGE_START,
	TCVAR_REFLECTION_LOD_RANGE_END,
	TCVAR_REFLECTION_SLOD_RANGE_START,
	TCVAR_REFLECTION_SLOD_RANGE_END,
	TCVAR_REFLECTION_INTERIOR_RANGE,
	TCVAR_REFLECTION_TWEAK_INTERIOR_AMB,
	TCVAR_REFLECTION_TWEAK_EXTERIOR_AMB,
	TCVAR_REFLECTION_TWEAK_EMISSIVE,
	TCVAR_REFLECTION_TWEAK_DIRECTIONAL,
	TCVAR_REFLECTION_HDR_MULT,

	TCVAR_FAR_CLIP,
	TCVAR_TEMPERATURE,
	TCVAR_PTFX_EMISSIVE_INTENSITY_MULT,
	TCVAR_VFXLIGHTNING_INTENSITY_MULT,
	TCVAR_VFXLIGHTNING_VISIBILITY,
	TCVAR_GPUPTFX_LIGHT_INTENSITY_MULT,
	TCVAR_NATURAL_AMBIENT_MULTIPLIER,
	TCVAR_ARTIFICIAL_INT_AMBIENT_MULTIPLIER,
	TCVAR_FOG_CUT_OFF,
	TCVAR_NO_WEATHER_FX,
	TCVAR_NO_GPU_FX,
	TCVAR_NO_RAIN,
	TCVAR_NO_RAIN_RIPPLES,
	TCVAR_FOGVOLUME_DENSITY_SCALAR,
	TCVAR_FOGVOLUME_DENSITY_SCALAR_INTERIOR,
	TCVAR_FOGVOLUME_FOG_SCALER,
	TCVAR_TIME_OFFSET,
	TCVAR_VEHICLE_DIRT_MOD,
	TCVAR_WIND_SPEED_MULT,
	TCVAR_ENTITY_REJECT,
	TCVAR_LOD_MULT,
	TCVAR_ENABLE_OCCLUSION,
	TCVAR_ENABLE_SHADOW_OCCLUSION,
	TCVAR_ENABLE_EXTERIOR,
	TCVAR_PORTAL_WEIGHT,

	TCVAR_LIGHT_FALLOFF_MULT,
	TCVAR_LODLIGHT_RANGE_MULT,
	TCVAR_SHADOW_DISTANCE_MULT,

	TCVAR_LOD_MULT_HD,
	TCVAR_LOD_MULT_ORPHANHD,
	TCVAR_LOD_MULT_LOD,
	TCVAR_LOD_MULT_SLOD1,
	TCVAR_LOD_MULT_SLOD2,
	TCVAR_LOD_MULT_SLOD3,
	TCVAR_LOD_MULT_SLOD4,

	TCVAR_NUM  
};

enum tcVarType_e
{
	VARTYPE_NONE = 0,
	VARTYPE_FLOAT,
	VARTYPE_COL3,
	VARTYPE_COL4,
};

struct tcVarInfo
{
	int					varId;
	const char*			name;
	tcVarType_e			varType;
	const char*			menuName;
	bool				InCategory = false;
};


extern tcVarInfo g_varInfos[TCVAR_NUM];
